import { defineConfig } from "vitest/config";

/**
 * Vitest workspace: lets `pnpm exec vitest` (and editor integrations) run every package's
 * unit tests in one process, and `pnpm test:coverage` measure them together.
 * CI and `pnpm test` still run per package through turbo.
 *
 * Vitest 工作区配置：让 `pnpm exec vitest`（以及编辑器插件）在一个进程中运行所有包的单元测试，
 * `pnpm test:coverage` 统一统计覆盖率。CI 和 `pnpm test` 仍通过 turbo 按包运行。
 */
export default defineConfig({
  test: {
    projects: [
      "{apps,packages}/*/vitest.config.ts",
      "contracts/vitest.config.ts",
      "evals/vitest.config.ts",
    ],
    coverage: {
      provider: "v8",
      reporter: ["text-summary", "html"],
      reportsDirectory: "coverage",
      include: [
        "apps/*/src/**/*.{ts,tsx}",
        "packages/*/src/**/*.{ts,tsx}",
        "contracts/src/**/*.ts",
        "evals/src/**/*.ts",
      ],
      // Entrypoints, generated code and test helpers are exercised by e2e or not code at all.
      // 入口文件、生成代码和测试辅助不计入（由 e2e 覆盖或本身不是业务代码）。
      exclude: [
        "**/*.test.{ts,tsx}",
        "**/*.int.test.ts",
        "**/*.gen.ts",
        "**/src/test/**",
        "apps/*/src/main.ts",
        "apps/*/src/instrument.ts",
        "apps/web/src/instrumentation*.ts",
        "packages/db/src/scripts/**",
        "packages/db/src/testing.ts",
        "evals/src/run.ts",
        // Vendored shadcn components (regenerated by `shadcn add`); exercised via web tests.
        // shadcn 生成的组件（由 `shadcn add` 重新生成），通过 web 的组件测试间接覆盖。
        "packages/ui/src/components/**",
      ],
      // Floors just under the current unit-test coverage; raise them as coverage grows,
      // never lower them to make a run pass (AGENTS.md §5).
      // 覆盖率下限，略低于当前单元测试的实际值；只能随覆盖率提高而上调，禁止为通过而下调。
      thresholds: { lines: 81, statements: 80, branches: 75, functions: 70 },
    },
  },
});
