/*
 * Tables required by Better Auth (email + password). Field names must match
 * Better Auth's core schema; the adapter is configured with `usePlural: true`.
 * IDs are generated by Better Auth, so they are text rather than uuid.
 *
 * Better Auth（邮箱 + 密码）所需的表。字段名必须与 Better Auth 核心 schema 一致，
 * 修改前先查 Better Auth 文档；ID 由 Better Auth 生成，所以是 text 而不是 uuid。
 */
import { boolean, index, pgTable, text, timestamp } from "drizzle-orm/pg-core";

const timestamps = {
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
};

/**
 * Registered users. `emailVerified` gates sign-in.
 *
 * 注册用户。`emailVerified` 为 false 时不能登录。
 */
export const users = pgTable("users", {
  id: text().primaryKey(),
  name: text().notNull(),
  email: text().notNull().unique(),
  emailVerified: boolean().notNull().default(false),
  image: text(),
  ...timestamps,
});

/**
 * Active sessions; `token` is the value behind the session cookie.
 *
 * 活动会话；`token` 即会话 Cookie 所对应的值。删除用户时级联删除。
 */
export const sessions = pgTable(
  "sessions",
  {
    id: text().primaryKey(),
    token: text().notNull().unique(),
    expiresAt: timestamp({ withTimezone: true }).notNull(),
    ipAddress: text(),
    userAgent: text(),
    userId: text()
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    ...timestamps,
  },
  (t) => [index().on(t.userId)],
);

/**
 * Login methods per user. Email/password logins use provider `"credential"`.
 *
 * 用户的登录方式。邮箱密码登录的 `providerId` 为 `"credential"`，OAuth 令牌字段为后续社交登录预留。
 */
export const accounts = pgTable(
  "accounts",
  {
    id: text().primaryKey(),
    accountId: text().notNull(),
    providerId: text().notNull(),
    userId: text()
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    accessToken: text(),
    refreshToken: text(),
    idToken: text(),
    accessTokenExpiresAt: timestamp({ withTimezone: true }),
    refreshTokenExpiresAt: timestamp({ withTimezone: true }),
    scope: text(),
    /** Password hash for the "credential" provider; never exposed outside the auth module. 密码哈希，只在鉴权模块内使用。 */
    password: text(),
    ...timestamps,
  },
  (t) => [index().on(t.userId)],
);

/**
 * Short-lived verification values (email verification, password reset).
 *
 * 短期有效的验证数据（邮箱验证、密码重置），过期后失效。
 */
export const verifications = pgTable(
  "verifications",
  {
    id: text().primaryKey(),
    identifier: text().notNull(),
    value: text().notNull(),
    expiresAt: timestamp({ withTimezone: true }).notNull(),
    ...timestamps,
  },
  (t) => [index().on(t.identifier)],
);
